apiVersion: v1
kind: ConfigMap
metadata:
  name: ldapguard-config
  namespace: {{ include "ldapguard.namespace" . }}
  labels:
    {{- include "ldapguard.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.config.debug | quote }}
  APP_NAME: "LDAPGuard"
  BACKUP_DIR: "/app/backups"
  BACKUP_RETENTION_DAYS: {{ .Values.config.backupRetentionDays | quote }}
  INCREMENTAL_BACKUP_ENABLED: {{ .Values.config.incrementalBackupEnabled | quote }}
  PROMETHEUS_ENABLED: {{ .Values.config.prometheusEnabled | quote }}
  PROMETHEUS_PORT: {{ .Values.config.prometheusPort | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.config.accessTokenExpireMinutes | quote }}
  ALGORITHM: "HS256"
  WEBHOOK_ENABLED: {{ .Values.config.webhookEnabled | quote }}
  REDIS_URL: "redis://redis:6379"
  POSTGRES_DB: "ldapguard"
  POSTGRES_USER: "ldapguard"
