apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: {{ include "ldapguard.namespace" . }}
  labels:
    {{- include "ldapguard.postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgres.storage.accessMode }}
  {{- if .Values.postgres.storage.storageClassName }}
  storageClassName: {{ .Values.postgres.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
