apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ldapguard-restrict
  namespace: ldapguard
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: ldapguard
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: ldapguard
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: ldapguard
