apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secrets.yaml        # Create from secrets.example.yaml
  - ingressroute.yaml   # Create from ingressroute.example.yaml

patchesStrategicMerge:
  - resource-limits.yaml  # Create from resource-limits.example.yaml

images:
  - name: ghcr.io/keundokki/ldapguard-api
    newTag: "0.0.5"
  - name: ghcr.io/keundokki/ldapguard-worker
    newTag: "0.0.5"
  - name: ghcr.io/keundokki/ldapguard-web
    newTag: "0.0.5"
