apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ include "ldapguard.namespace" . }}
  labels:
    {{- include "ldapguard.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ldapguard.name" . }}
    app.kubernetes.io/component: api
