apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ include "ldapguard.namespace" . }}
  labels:
    {{- include "ldapguard.postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.postgres.type }}
  ports:
    - port: {{ .Values.service.postgres.port }}
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/name: {{ include "ldapguard.name" . }}
    app.kubernetes.io/component: postgres
