apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ include "ldapguard.namespace" . }}
  labels:
    {{- include "ldapguard.redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.redis.type }}
  ports:
    - port: {{ .Values.service.redis.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ include "ldapguard.name" . }}
    app.kubernetes.io/component: redis
