apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ include "ldapguard.namespace" . }}
  labels:
    {{- include "ldapguard.web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ldapguard.name" . }}
    app.kubernetes.io/component: web
