apiVersion: v2
name: ldapguard
description: A Helm chart for LDAPGuard - Secure LDAP backup and restore solution
type: application
version: 0.1.0
appVersion: "0.0.7"
keywords:
  - ldap
  - backup
  - security
  - openldap
home: https://github.com/keundokki/LDAPGuard
sources:
  - https://github.com/keundokki/LDAPGuard
maintainers:
  - name: keundokki
    url: https://github.com/keundokki
icon: https://raw.githubusercontent.com/keundokki/LDAPGuard/main/web/favicon.ico
